version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ayurherb-ganache
    ports:
      - "8546:8545"
    command: [
      "--host", "0.0.0.0",
      "--port", "8545",
      "--networkId", "1337",
      "--gasLimit", "10000000",
      "--gasPrice", "0",
      "--accounts", "10",
      "--ether", "1000",
      "--deterministic",
      "--mnemonic", "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    ]
    networks:
      - ayurherb-network

networks:
  ayurherb-network:
    driver: bridge
